<<<<<<< HEAD
import json
import os
import secrets
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow


BASE_DIR = Path(__file__).resolve().parents[2]

load_dotenv(BASE_DIR / ".env")


CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")

REDIRECT_URI = os.getenv(
    "GOOGLE_REDIRECT_URI",
    "http://localhost:8000/api/gmail/callback",
)


TOKEN_FILE = BASE_DIR / "data" / "gmail_token.json"


SCOPES = [
    "https://www.googleapis.com/auth/gmail.send",
]


# OAuth state -> PKCE code verifier
#
# The verifier MUST survive from the moment the authorization URL
# is generated until Google redirects back to the callback.
#
# This is kept in memory for local/single-process development.
_oauth_states: dict[str, str] = {}


def create_flow() -> Flow:
    """
    Create and configure a Google OAuth Flow.
    """

    if not CLIENT_ID:
        raise RuntimeError(
            "GOOGLE_CLIENT_ID is missing from .env"
        )

    if not CLIENT_SECRET:
        raise RuntimeError(
            "GOOGLE_CLIENT_SECRET is missing from .env"
        )

    client_config = {
        "web": {
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": [
                REDIRECT_URI
            ],
        }
    }

    flow = Flow.from_client_config(
        client_config,
        scopes=SCOPES,
    )

    flow.redirect_uri = REDIRECT_URI

    return flow


def create_authorization_url():
    """
    Generate the Google authorization URL.

    The PKCE verifier generated by google-auth-oauthlib is stored
    against the OAuth state so it can be restored during callback.
    """

    flow = create_flow()

    # Generate our own CSRF state.
    state = secrets.token_urlsafe(32)

    authorization_url, _ = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",
        state=state,
    )

    # IMPORTANT:
    # The same verifier generated for this authorization request
    # must be supplied when exchanging the authorization code.
    code_verifier = getattr(flow, "code_verifier", None)

    if not code_verifier:
        raise RuntimeError(
            "Google OAuth did not generate a PKCE code verifier."
        )

    _oauth_states[state] = code_verifier

    return authorization_url, state


def exchange_code(
    authorization_response: str,
    state: str,
):
    """
    Exchange Google's authorization code for credentials.

    The PKCE code verifier saved during create_authorization_url()
    is restored onto the new Flow before fetch_token().
    """

    if not state:
        raise ValueError(
            "Missing OAuth state."
        )

    code_verifier = _oauth_states.pop(state, None)

    if not code_verifier:
        raise ValueError(
            "Missing or expired OAuth code verifier."
        )

    flow = create_flow()

    # Restore the verifier from the original authorization request.
    flow.code_verifier = code_verifier

    try:
        flow.fetch_token(
            authorization_response=authorization_response,
        )

    except Exception:
        # Do not leave stale credentials/state around if token
        # exchange fails.
        raise

    credentials = flow.credentials

    if not credentials:
        raise RuntimeError(
            "Google OAuth returned no credentials."
        )

    save_credentials(credentials)

    return credentials


def save_credentials(
    credentials: Credentials,
):
    """
    Persist Gmail OAuth credentials to disk.
    """

    TOKEN_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    data = {
        "token": credentials.token,
        "refresh_token": credentials.refresh_token,
        "token_uri": credentials.token_uri,
        "client_id": credentials.client_id,
        "client_secret": credentials.client_secret,
        "scopes": credentials.scopes,
    }

    TOKEN_FILE.write_text(
        json.dumps(
            data,
            indent=2,
        ),
        encoding="utf-8",
    )


def load_credentials() -> Optional[Credentials]:
    """
    Load stored Gmail credentials.

    Automatically refreshes an expired access token when a
    refresh token is available.
    """

    if not TOKEN_FILE.exists():
        return None

    try:
        credentials = Credentials.from_authorized_user_file(
            str(TOKEN_FILE),
            SCOPES,
        )

    except Exception:
        return None

    if (
        credentials
        and credentials.expired
        and credentials.refresh_token
    ):
        try:
            credentials.refresh(Request())

            save_credentials(credentials)

        except Exception:
            return None

    if credentials and credentials.valid:
        return credentials

    return None


def delete_credentials():
    """
    Disconnect Gmail by deleting the stored OAuth credentials.
    """

    if TOKEN_FILE.exists():
        TOKEN_FILE.unlink()


def is_connected() -> bool:
    """
    Return True when valid Gmail OAuth credentials exist.
    """

=======
import json
import os
import secrets
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow


BASE_DIR = Path(__file__).resolve().parents[2]

load_dotenv(BASE_DIR / ".env")


CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")

REDIRECT_URI = os.getenv(
    "GOOGLE_REDIRECT_URI",
    "http://localhost:8000/api/gmail/callback",
)


TOKEN_FILE = BASE_DIR / "data" / "gmail_token.json"


SCOPES = [
    "https://www.googleapis.com/auth/gmail.send",
]


# OAuth state -> PKCE code verifier
#
# The verifier MUST survive from the moment the authorization URL
# is generated until Google redirects back to the callback.
#
# This is kept in memory for local/single-process development.
_oauth_states: dict[str, str] = {}


def create_flow() -> Flow:
    """
    Create and configure a Google OAuth Flow.
    """

    if not CLIENT_ID:
        raise RuntimeError(
            "GOOGLE_CLIENT_ID is missing from .env"
        )

    if not CLIENT_SECRET:
        raise RuntimeError(
            "GOOGLE_CLIENT_SECRET is missing from .env"
        )

    client_config = {
        "web": {
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": [
                REDIRECT_URI
            ],
        }
    }

    flow = Flow.from_client_config(
        client_config,
        scopes=SCOPES,
    )

    flow.redirect_uri = REDIRECT_URI

    return flow


def create_authorization_url():
    """
    Generate the Google authorization URL.

    The PKCE verifier generated by google-auth-oauthlib is stored
    against the OAuth state so it can be restored during callback.
    """

    flow = create_flow()

    # Generate our own CSRF state.
    state = secrets.token_urlsafe(32)

    authorization_url, _ = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",
        state=state,
    )

    # IMPORTANT:
    # The same verifier generated for this authorization request
    # must be supplied when exchanging the authorization code.
    code_verifier = getattr(flow, "code_verifier", None)

    if not code_verifier:
        raise RuntimeError(
            "Google OAuth did not generate a PKCE code verifier."
        )

    _oauth_states[state] = code_verifier

    return authorization_url, state


def exchange_code(
    authorization_response: str,
    state: str,
):
    """
    Exchange Google's authorization code for credentials.

    The PKCE code verifier saved during create_authorization_url()
    is restored onto the new Flow before fetch_token().
    """

    if not state:
        raise ValueError(
            "Missing OAuth state."
        )

    code_verifier = _oauth_states.pop(state, None)

    if not code_verifier:
        raise ValueError(
            "Missing or expired OAuth code verifier."
        )

    flow = create_flow()

    # Restore the verifier from the original authorization request.
    flow.code_verifier = code_verifier

    try:
        flow.fetch_token(
            authorization_response=authorization_response,
        )

    except Exception:
        # Do not leave stale credentials/state around if token
        # exchange fails.
        raise

    credentials = flow.credentials

    if not credentials:
        raise RuntimeError(
            "Google OAuth returned no credentials."
        )

    save_credentials(credentials)

    return credentials


def save_credentials(
    credentials: Credentials,
):
    """
    Persist Gmail OAuth credentials to disk.
    """

    TOKEN_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    data = {
        "token": credentials.token,
        "refresh_token": credentials.refresh_token,
        "token_uri": credentials.token_uri,
        "client_id": credentials.client_id,
        "client_secret": credentials.client_secret,
        "scopes": credentials.scopes,
    }

    TOKEN_FILE.write_text(
        json.dumps(
            data,
            indent=2,
        ),
        encoding="utf-8",
    )


def load_credentials() -> Optional[Credentials]:
    """
    Load stored Gmail credentials.

    Automatically refreshes an expired access token when a
    refresh token is available.
    """

    if not TOKEN_FILE.exists():
        return None

    try:
        credentials = Credentials.from_authorized_user_file(
            str(TOKEN_FILE),
            SCOPES,
        )

    except Exception:
        return None

    if (
        credentials
        and credentials.expired
        and credentials.refresh_token
    ):
        try:
            credentials.refresh(Request())

            save_credentials(credentials)

        except Exception:
            return None

    if credentials and credentials.valid:
        return credentials

    return None


def delete_credentials():
    """
    Disconnect Gmail by deleting the stored OAuth credentials.
    """

    if TOKEN_FILE.exists():
        TOKEN_FILE.unlink()


def is_connected() -> bool:
    """
    Return True when valid Gmail OAuth credentials exist.
    """

>>>>>>> 584b136ab801c7a8b9073ed3b1816c8cd59aac82
    return load_credentials() is not None